### ISSUE TITLE
resetSizeOfImage:

### ISSUE THREAD

**Issue by Meterwhite** [KirstenDunst/CSXImageCompress#1]
你好，你不应该使用异步的方法提供给开发者，是否异步应该由开发者决定比较好。

**Comment by KirstenDunst** [comment]
你好，我觉得你应该只是看到了demo中的循环压缩，其实这不是重点。主要的是图片压缩的处理方法。批量循环是让大家来看这个方法的优越性的。demo的初衷是这个意思的！也谢谢你的关注，喜欢的话关注我一下吧，并送上你的star吧！发自我的iPhone------------------ Original ------------------From: Meterwhite  <notifications@github.com>Date: Tue,Dec 24,2019 5:42 PMTo: KirstenDunst/CSXImageCompress <CSXImageCompress@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [KirstenDunst/CSXImageCompress] resetSizeOfImage: (#1)你好，你不应该使用异步的方法提供给开发者，是否异步应该由开发者决定比较好。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KirstenDunst/CSXImageCompress/issues/1?email_source=notifications\u0026email_token=AEY5CDQIMXANHFW2MCPUNT3Q2HKQ3A5CNFSM4J64UEJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ICPIZRQ",
"url": "https://github.com/KirstenDunst/CSXImageCompress/issues/1?email_source=notifications\u0026email_token=AEY5CDQIMXANHFW2MCPUNT3Q2HKQ3A5CNFSM4J64UEJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ICPIZRQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
